name: fit_fast_web
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  flutter_typeahead: ^4.0.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  flutter_svg: ^1.1.3
  dropdown_button2: ^1.7.2
  fit_fast_core:
    path: ../fit_fast_core


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/svg/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Objective
      fonts:
        - asset: assets/fonts/Objective/Objective-Regular.otf
        - asset: assets/fonts/Objective/Objective-Black.otf
        - asset: assets/fonts/Objective/Objective-Black-Italic.otf
        - asset: assets/fonts/Objective/Objective-Bold.otf
        - asset: assets/fonts/Objective/Objective-Bold-Italic.otf
        - asset: assets/fonts/Objective/Objective-ExtraBold.otf
        - asset: assets/fonts/Objective/Objective-ExtraBold-Italic.otf
        - asset: assets/fonts/Objective/Objective-Italic.otf
        - asset: assets/fonts/Objective/Objective-Light.otf
        - asset: assets/fonts/Objective/Objective-Light-Italic.otf
        - asset: assets/fonts/Objective/Objective-Medium.otf
        - asset: assets/fonts/Objective/Objective-Medium-Italic.otf
        - asset: assets/fonts/Objective/Objective-Super.otf
        - asset: assets/fonts/Objective/Objective-Super-Italic.otf
        - asset: assets/fonts/Objective/Objective-Thin.otf
        - asset: assets/fonts/Objective/Objective-Thin-Italic.otf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
